name: Package release

on:
  release:
    types: [created]
  workflow_dispatch:


jobs:
  deploy_osx:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

        run: ${GITHUB_WORKSPACE}/.github/workflows/scripts/release_osx.sh

  deploy_linux:
    strategy:
      matrix:
        python-version:
          - cp39-cp39
          - cp310-cp310

    runs-on: ubuntu-latest
    container:
      image: node:20-bullseye  # Use the official Node.js 20 image based on Debian
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set target Python version PATH
        run: |
          echo "/opt/python/${{ matrix.python-version }}/bin" >> $GITHUB_PATH
      - name: Install Python Build Dependencies
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3-dev build-essential
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: ${GITHUB_WORKSPACE}/.github/workflows/scripts/release_linux.sh

  deploy_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          ../../.github/workflows/scripts/release_windows.bat
